name: Daily Load and Assemble

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 02:00 UTC
  workflow_dispatch:  # Allows the workflow to be manually triggered

jobs:
  load-and-assemble:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run load script for previous date
        run: |
          YESTERDAY=$(date -d "yesterday" '+%Y-%m-%d')
          echo "Running load.py for date: $YESTERDAY"
          python load.py --date "$YESTERDAY"

      - name: Run assemble script
        run: |
          echo "Running assemble.py"
          python assemble.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/ output.json output_daily.json
          git commit -m "Update data and output.json for $YESTERDAY"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
