name: Daily Load and Assemble

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 03:00 UTC
  workflow_dispatch:  # Allows the workflow to be manually triggered

jobs:
  load-and-assemble:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run load script for previous date
        run: |
          YESTERDAY=$(date -d "yesterday" '+%Y-%m-%d')
          echo "Running load.py for date: $YESTERDAY"
          python load.py --date "$YESTERDAY"

      - name: Run assemble script
        run: |
          echo "Running assemble.py"
          python assemble.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          BRANCH_NAME="data-update-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $BRANCH_NAME
          git add data/ output.json output_daily.json
          git commit -m "Update data and output.json for $YESTERDAY"
          git push origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: $BRANCH_NAME
          title: "Daily data update for $YESTERDAY"
          body: "This pull request contains the daily data update for $YESTERDAY."
          base: main

      - name: Merge pull request
        if: steps.create_pr.outputs.pull-request-url
        run: |
          PR_NUMBER=$(basename $(steps.create_pr.outputs.pull-request-url))
          gh pr merge $PR_NUMBER --squash --admin --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}

      - name: Delete branch if merge is successful
        if: steps.create_pr.outputs.pull-request-url
        run: |
          git push origin --delete $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
