name: Run Daily Scripts

on:
  schedule:
    - cron: "0 3 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create new branch
        id: create_branch
        run: |
          BRANCH_NAME="daily-run-$(date +'%Y-%m-%d')"
          git checkout -b $BRANCH_NAME
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Run load.py
        run: |
          PREV_DATE=$(date -d "yesterday" '+%Y-%m-%d')
          python load.py --date $PREV_DATE

      - name: Run assemble.py
        run: python assemble.py

      - name: commit and push
        run: |
          git add .
          git commit -m "Daily run for $(date +'%Y-%m-%d')"
          git push --set-upstream origin $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Daily run for $(date +'%Y-%m-%d')"
          branch: ${{ steps.create_branch.outputs.branch }}
          base: main
          delete-branch: false # Automatically deletes the branch after merging
